config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  resources :houses
  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end
  root "static_pages#index"
  get "/users/profile", to: "static_pages#profile"

  put "active_host" => "users#active_host"

  post "/comment" => "comments#create"
  post "/care" => "cares#create"
  delete "/care/:id" => "cares#destroy"

  # city houses
  get "/houses/city/:id" => "houses#houses_city"

  # get notification
  get "/users/notifications/:id" => "users#pull_notification_by_recived_id"
  # update status notification
  get "/users/notifications/update/:id" => "users#update_notification_by_id"

  resources :house_photos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #import data
  resources :houses do
    collection { post :import }
  end
  resources :house_photos do
    collection { post :import }
  end
  resources :comments do
    collection { post :import }
  end
  resources :cares do
    collection { post :import }
  end
end

app/views/shared/home_page/_footer.html.erb
<section class="w3l-footers-20 footer-home">
  <div class="footers20">
    <div class="container">
      <div class="footers20-content">
        <div class="d-grid grid-col-3 grids-content1 bottom-border">
          <div class="columns copyright-grid align-self">
            <p class="copy-footer-29">© Welcome to FHouse, TODAY I FEEL SO
              <a href="https://w3layouts.com">
                GOOD
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <button onclick="topFunction()" id="movetop" title="Go to top">
    &#10548;
  </button>
</section>

app/views/shared/home_page/_location_preview.html.erb
<div class="col-lg-3 col-md-4 col-6 pt-5">
  <%= link_to "/houses/city/#{local_assigns[:name]}" do %>
    <div class="box16">
      <img style="width: 270px; height: 200px" class="img-fluid" src=<%= local_assigns[:image] %> alt=<%= local_assigns[:name] %>>
      <div class="box-content">
        <h3 class="title mb-1">TP. <%= local_assigns[:name] %></h3>
        <span class="post"><%= House.where(city: local_assigns[:name]).size || 0 %> Nhà đang được cho thuê</span>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/home_page/_post_preview.html.erb
<div class="col-lg-4 col-md-6 pt-4">
  <%= link_to house_path(local_assigns[:house][:house]) do %>
    <div class="box16">
      <div class="rentext-listing-category">
        <span>Rent</span>
        <span>
          <%= local_assigns[:house][:house][:view] || 0 %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
            <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
          </svg>
        </span>
        <span>
          <%= local_assigns[:house][:comments] || 0 %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-text-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM4.5 5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4z"/>
          </svg>
        </span>
        <span>
          <%= local_assigns[:house][:cares] || 0 %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
            <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
          </svg>
        </span>
      </div>
      <img src=<%= local_assigns[:house][:img] %> class="img-fluid" style="height: 300px" alt="" />
      <div class="box-content">
        <h3 class="title"><%= local_assigns[:house][:house][:title] %></h3>
        <h3 class="title"><%= local_assigns[:house][:house][:pice] %> VND</h3>
        <span class="post"><%= local_assigns[:house][:house][:address] %></span>
      </div>
    </div>
  <% end %>
</div>