config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  resources :houses
  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end
  root "static_pages#index"
  get "/users/profile", to: "static_pages#profile"

  put "active_host" => "users#active_host"

  post "/comment" => "comments#create"
  post "/care" => "cares#create"
  delete "/care/:id" => "cares#destroy"

  # city houses
  get "/houses/city/:id" => "houses#houses_city"

  # get notification
  get "/users/notifications/:id" => "users#pull_notification_by_recived_id"
  # update status notification
  get "/users/notifications/update/:id" => "users#update_notification_by_id"

  resources :house_photos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #import data
  resources :houses do
    collection { post :import }
  end
  resources :house_photos do
    collection { post :import }
  end
  resources :comments do
    collection { post :import }
  end
  resources :cares do
    collection { post :import }
  end
end

app/views/layouts/_header.html.erb
<div class="header-page">
  <header id="site-header" class="fixed-top">
    <div class="container">
      <nav class="navbar navbar-expand-lg stroke px-0">
        <h1>
          <%= link_to root_path, :class => 'navbar-brand' do %>
            <span class="fa fa-home"></span> FHouse
          <% end %>
        </h1>
        <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse"
          data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
          <span class="navbar-toggler-icon fa icon-close fa-times"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-lg-5 mr-auto">
            <% if user_signed_in? %>
              <div class="dropdown ml-3 btn-account-mobile">
                <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username %>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownAccount">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  <%= link_to "Profile", users_profile_path, class: "dropdown-item" %>
                  <% if (current_user.role == "user") %>
                    <%= link_to "Active Host", active_host_path, method: :put, class: "dropdown-item" %>
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="btn-account-mobile">
                <%= link_to signin_path do %>
                  <div class="btn btn-primary">
                    Đăng nhập
                  </div>
                <% end %>
              </div>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <div class="">
                  <% if !(current_user.role == "host") && !current_user.request_host  %>
                    <% if user_signed_in? && ["admin@gmail.com"].include?(current_user.email) %>
                      <a style="border-bottom: 5px solid #f93;" class="nav-link" href="/admin">Quản lý <span class="fa fa-home"></span></a>
                    <% else %>
                      <%= link_to "Active Host", active_host_path, method: :put, class: "btn btn-primary" %>
                    <% end %>
                  <% elsif current_user.role == "host" %>
                    <% if user_signed_in? && ["host"].include?(current_user.role) %>
                      <a style="border-bottom: 5px solid #f93;" class="nav-link" href="/admin">Quản lý <span class="fa fa-home"></span></a>
                    <% end %>
                  <% else %>
                    <div class="btn btn-primary">
                      Enable Host Pending
                    </div>
                  <% end %>
                </div>
              <% end %>
            </li>
          </ul>
          <% if current_user && (current_user.role == "host") %>
            <div class="top-quote mt-lg-0">
              <%= link_to new_house_path, class: "btn btn-style btn-primary" do %>
                <span class="fa fa-home"></span> THÊM
              <% end %>
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="ml-3 my-noti-header">
            <div class="icon" id="bell">
              <img src="https://i.imgur.com/AC7dgLA.png" alt="">
              <span data-user=<%= current_user.id %> id="badge-notification" class="badge badge-light display_none">0</span>
            </div>
            <div class="notifications my-notification-box" id="box">
            </div>
          </div>
        <% end %>
        <div class="mobile-position ml-3">
          <nav class="navigation">
            <div class="theme-switch-wrapper">
              <label class="theme-switch" for="checkbox">
                <input type="checkbox" id="checkbox">
                <div class="mode-container">
                  <i class="gg-sun"></i>
                  <i class="gg-moon"></i>
                </div>
              </label>
            </div>
          </nav>
        </div>
        <div>
          <% if user_signed_in? %>
            <div class="dropdown ml-3 btn-account">
              <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </button>
              <div class="dropdown-menu box-drop-account" aria-labelledby="dropdownAccount">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                <%= link_to "Profile", users_profile_path, class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <div class="ml-4">
              <%= link_to signin_path do %>
                <div class="btn btn-primary">
                  Đăng nhập
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </nav>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <title>Fhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>
  <body>
    <div id="root_header">
      <%= render "layouts/header" %>
    </div>
    <%= yield %>
  </body>
  <%= javascript_pack_tag 'template', 'data-turbolinks-track': 'reload' %>
</html>